openapi: 3.0.3
info:
  title: TrainIt
  version: 1.0.ß

servers:
  - url: 'http://localhost:8085/api'

paths:
  /login/{userName}/{password}:
    get:
      operationId: checkLogin
      description: Check if User is known
      parameters:
        - $ref: '#/components/parameters/userName'
        - $ref: '#/components/parameters/password'
      responses: 
        200:
          $ref: '#/components/responses/UserResponse'

  /login/create/{userName}/{password}:
    put:
      operationId: createUser
      description: create User if he does not already Exists
      parameters:
        - $ref: '#/components/parameters/userName'
        - $ref: '#/components/parameters/password'
      responses:
        200:
          description: ok
        400:
          description: User is already known


components:
  responses:
    UserResponse:
      description: OK
      content:
          application/json:
            schema:
              type: object
              $ref: '#/components/schemas/RunnerDto'

  parameters:
    userName:
      name: userName
      in: path
      required: true
      schema:
        type: string

    password:
      name: password
      in: path
      required: true
      schema:
        type: string
            
  schemas:
    RunnerDto:
      required:
        - "name"
        - "totalRuns"
      description: Return Object of an User
      type: object
      properties:
        name:
          type: string
        totalRuns:
          type: integer  
